### ISSUE TITLE
Seeking support

### ISSUE THREAD

**Issue by faroit** [pyminimp3/pyminimp3#8]
I just found this python interface. I would love to benchmark this in [my audio loading comparions](https://github.com/faroit/python_audio_loading_benchmark/).
A few questions:

* Does it support seeking?
* Besides the tests dir, is there some usage documentation?
* Do you plan to upload the package to pypi?

**Comment by pganssle** [comment]
Hey, sorry it took me so long to respond to this. I'm sorta buried in other work these days.

1. Does it support seeking?

It should; the actual *raison d'être* of this library was to allow you to lazily load an arbitrary portion of an MP3 file in Python, and `minimp3` seems like an ideal way to accomplish this.

2. Besides the tests dir, is there some usage documentation?

Not yet. The main issue is that I have a thin wrapper around minimp3 here, but I planned to write a higher-level "pythonic" Python API for it and haven't gotten around to it quite yet, so there's not really anything to document since the user-facing portions of the library have not yet been designed.

I have spawned issue #9 to track this. It seems like you have a decent handle on the current landscape for audio loading and handling; it seems like you may have some familiarity with the landscape for audio loading tools, so if you want to make some proposals on this front it would be very appreciated.

3. Do you plan to upload the package to pypi?

Yes. Again this is primarily blocked on #9, though I also have some work to do on factoring the tests in such a way that the repo doesn't explode in size from having a bunch of FLAC files plus a bunch of different encodings in it, though that last part doesn't have to be a blocker.

**Comment by faroit** [comment]
Happy to help out. I would love to make some benchmarks using minimp3. Closing this for now to focus on the main discussion in #9.
